# Generated by Django 5.0a1 on 2023-10-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='text_advice',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='mood',
            name='my_mood',
            field=models.CharField(choices=[('angry', 'angry'), ('annoyed', 'annoyed'), ('sad', 'sad'), ('very sad', 'very sad'), ('fine', 'fine'), ('mischievous', 'mischievous'), ('excited', 'excited'), ('playful', 'playful'), ('boder', 'boder'), ('sick', 'sick'), ('sleepy', 'sleepy'), ('surprised', 'surprised'), ('unhappy', 'unhappy'), ('grumpy', 'grumpy')], max_length=25),
        ),
    ]
