# Generated by Django 5.0a1 on 2023-10-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notey_app', '0002_alter_advice_text_advice_alter_mood_my_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='my_mood',
            field=models.CharField(choices=[('angry', 'angry'), ('annoyed', 'annoyed'), ('sad', 'sad'), ('very sad', 'very sad'), ('fine', 'fine'), ('mischievous', 'mischievous'), ('excited', 'excited'), ('playful', 'playful'), ('bored', 'bored'), ('sick', 'sick'), ('sleepy', 'sleepy'), ('surprised', 'surprised'), ('unhappy', 'unhappy'), ('grumpy', 'grumpy')], max_length=25),
        ),
    ]
