# Generated by Django 5.0a1 on 2023-10-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notey_app', '0003_alter_mood_my_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='my_mood',
        ),
        migrations.AddField(
            model_name='advice',
            name='mood_option',
            field=models.CharField(choices=[('angry', 'angry'), ('annoyed', 'annoyed'), ('sad', 'sad'), ('very sad', 'very sad'), ('fine', 'fine'), ('mischievous', 'mischievous'), ('excited', 'excited'), ('playful', 'playful'), ('bored', 'bored'), ('sick', 'sick'), ('sleepy', 'sleepy'), ('surprised', 'surprised'), ('unhappy', 'unhappy'), ('grumpy', 'grumpy')], default='-', max_length=25),
            preserve_default=False,
        ),
    ]
