# Generated by Django 5.0a1 on 2023-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notey_app', '0007_note_category_alter_advice_mood_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.TextField(blank=True, max_length='60', null=True),
        ),
    ]
