# Generated by Django 5.0a1 on 2023-11-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notey_app', '0010_mood_created_by_alter_note_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='created_by',
            new_name='author',
        ),
    ]
